#!/usr/bin/env python
# -*- coding:utf-8 -*-

class Gene:
  def __init__ (self,sequence,source,element,debut,fin,score,brin,phase,attributs):
    self.sequence=sequence
    self.source=source
    self.element=element
    self.debut=debut
    self.fin=fin
    self.score=score
    self.brin=brin
    self.phase=phase
    self.attributs=attributs
  
  
