#!/usr/bin/env python
# -*- coding:utf-8 -*-

import os
import sys
import gzip
import logging

class Files(object):
  def __init__(self, File):
    self._fos = File
    
  def __iter__(self):
    try:
      if self._fos.lower().endswith(('.gz', '.gzip')):
        fp = gzip.open(self._fos)
    except:
      printf("un des fichiers proposés n'es pas en .gz ou .gzip")    
    
    for index, line in enumerate(fp):
      if index % 50000 == 0 and index != 0:
        logger.info('working on line NO. of {}: {:,}'.format(os.path.basename(self._fos), index))
          line = line.decode()
            yield line
    fp.close()
